name:                fp-course
version:             0.1.0.0
github:              "daniel-manning/fp-course"
license:             BSD3
author:              "Tony Morris <tmorris@tmorris.net>
                      Mark Hibberd <mthibberd@gmail.com>
                      Ben Sinclair <ben.d.sinclair@gmail.com>
                      James Earl Douglas <james@earldouglas.com>
                      Eric Torreborre <etorreborre@yahoo.com>"
maintainer:          "Tony Morris"
copyright:           "Copyright (C) 2010-2013 Tony Morris
                      Copyright (C) 2012-2015 National ICT Australia Limited
                      Copyright (C) 2012      James Earl Douglas
                      Copyright (C) 2012      Ben Sinclair
                      Copyright (C) 2016-2017 Data61"
synopsis:             "Source code for a functional programming course"
category:             "Education"
description:          "Source code for a course in functional programming using Haskell"
homepage:             "https://github.com/data61/fp-course"
bug-reports:          "https://github.com/data61/fp-course/issues"
cabal-version:        ">= 1.10"

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.4
  - array >= 0.4
  - HUnit >= 1.6.0.0
  - QuickCheck >= 2.12.6.1
  - tasty >= 1.2
  - tasty-hunit >= 0.10.0.1
  - tasty-quickcheck >= 0.10
  - ansi-terminal >= 0.9
  - async >= 2.2.1
  - call-stack >= 0.1.0
  - clock >= 0.7.2
  - erf >= 2.0.0.0
  - optparse-applicative >= 0.14.3.0
  - random >= 1.1
  - tagged >= 0.8.6
  - tf-random >= 0.5
  - unbounded-delays >= 0.1.1.0
  - wcwidth >= 0.0.2
  - ansi-wl-pprint >= 0.6.8.2
  - colour >= 2.3.4
  - hashable >= 1.2.7.0
  - primitive >= 0.6.4.0
  - transformers-compat >= 0.6.2
  - aeson >= 1.4.2.0
  - cmdargs >= 0.10.20
  - cpphs >= 1.20.8
  - data-default >= 0.7.1.1
  - extra >= 1.6.14
  - haskell-src-exts >= 1.21.0
  - haskell-src-exts-util >= 0.2.4
  - hscolour >= 1.24.4
  - refact >= 0.3.0.2
  - uniplate >= 1.6.12
  - unordered-containers >= 0.2.10.0
  - vector >= 0.12.0.2
  - yaml >= 0.11.0.0
  - attoparsec >= 0.13.2.2
  - base-compat >= 0.10.5
  - conduit >= 1.3.1
  - contravariant >= 1.5
  - data-default-class >= 0.1.2.0
  - data-default-instances-containers >= 0.0.1
  - data-default-instances-dlist >= 0.0.1
  - data-default-instances-old-locale >= 0.0.1
  - dlist >= 0.8.0.5
  - happy >= 1.19.9
  - libyaml >= 0.1.0.0
  - old-locale >= 1.0.0.7
  - old-time >= 1.1.0.3
  - polyparse >= 1.12.1
  - resourcet >= 1.2.2
  - scientific >= 0.3.6.2
  - semigroups >= 0.18.5
  - syb >= 0.7
  - th-abstraction >= 0.2.10.0
  - time-locale-compat >= 0.1.1.5
  - uuid-types >= 1.0.3
  - StateVar >= 1.1.1.1
  - exceptions >= 0.10.0
  - integer-logarithms >= 1.0.2.2
  - mono-traversable >= 1.0.10.0
  - unliftio-core >= 0.1.2.0
  - split >= 0.2.3.3
  - vector-algorithms >= 0.8.0.1



library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-imports
  - -fno-warn-type-defaults
  - -ferror-spans

  default-extensions: NoImplicitPrelude
    ScopedTypeVariables
    InstanceSigs

  hs-source-dirs:     src
